[project]
name = "mlx-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataclasses>=0.8",
    "mlx>=0.21.1",
    "numpy>=2.2.0",
    "pillow>=11.0.0",
    "ruff>=0.8.2",
]
